export const recentActivitiesList = [
  {
    id: 1,
    name: "ETH-CORE",
    imgSrc: "ETH-CORE.svg",
    imgAlt: "ETH-CORE",
    type: "Cluster",
    amount: "$123.13",
    status: "Join Cluster",
    time: "12:50:15 AM",
  },
  {
    id: 2,
    name: "Poly Gaming",
    imgSrc: "Poly-Gaming.svg",
    imgAlt: "Poly Gaming",
    type: "Cluster",
    amount: "$100,123.25",
    status: "Unstake Cluster",
    time: "12:23:54 AM",
  },
  {
    id: 3,
    name: "ETH-CORE",
    imgSrc: "ETH-CORE.svg",
    imgAlt: "ETH-CORE",
    type: "Cluster",
    amount: "$1,543.00",
    status: "Stake Cluster",
    time: "11:47:22 AM",
  },
  {
    id: 4,
    name: "Polycluster",
    imgSrc: "Polycluster.svg",
    imgAlt: "Polycluster",
    type: "Cluster",
    amount: "$543.00",
    status: "Leave Cluster",
    time: "11:34:57 AM",
  },
  {
    id: 5,
    name: "WMATIC / WTH",
    imgSrc: "WMATIC.svg",
    imgAlt: "WMATIC / WTH",
    type: "Impulse",
    amount: "$1,124.47",
    status: "Stake Impulse",
    time: "11:47:22 AM",
  },
  {
    id: 6,
    name: "Polycluster",
    imgSrc: "Polycluster.svg",
    imgAlt: "Polycluster",
    type: "Cluster",
    amount: "$22.36",
    status: "Claim Rewards",
    time: "11:34:57 AM",
  },
  {
    id: 7,
    name: "WMATIC / WTH",
    imgSrc: "WMATIC.svg",
    imgAlt: "WMATIC / WTH",
    type: "Impulse",
    amount: "$1,124.47",
    status: "Stake Impulse",
    time: "11:47:22 AM",
  },
  {
    id: 8,
    name: "Poly Gaming",
    imgSrc: "Poly-Gaming.svg",
    imgAlt: "Poly Gaming",
    type: "Cluster",
    amount: "$3,422.36",
    status: "Claim Rewards",
    time: "11:34:57 AM",
  },
];
